spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transfers
    username: astronova
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect